### ISSUE TITLE
Incorrect Image Set in the Simple CMS application Folder

### ISSUE THREAD

**Issue by Aryan-Bhargav8** [LiquidGalaxyLAB/Data#32]
### The image set currently uploaded in the Simple CMS folder is incorrect. The uploaded images belong to the Liquid Galaxy Controller, which is not related to the Simple CMS application.

**Current Image Set (Incorrect)**
The following images are currently uploaded in the folder but belong to the Liquid Galaxy Controller:
![image](https://github.com/user-attachments/assets/a2a44b3b-e616-4278-9468-fa0d1daa0ec7)
![image](https://github.com/user-attachments/assets/59a09637-c762-463e-9e4b-8b4f875e851b)

**Correct Image Set**
The correct image set for the Simple CMS application is as follows:
![image](https://github.com/user-attachments/assets/df2a6b04-c5eb-4314-b6b1-418110c8fe56)
![image](https://github.com/user-attachments/assets/2240b6a0-1270-4dfb-8e5f-fc71744634fc)

**Steps to Resolve:**
- Replace the incorrect images with the correct ones listed above.
- Ensure all the folders are reviewed for any other discrepancies.

**Comment by yashrajbharti** [comment]
feel free to fix it with a PR, thanks!
