### ISSUE TITLE
Reupload some app icons

### ISSUE THREAD

**Issue by yashrajbharti** [LiquidGalaxyLAB/Data#49]
LG AIS visualizer : must be uploaded in 1:1 ratio

BYOP : stretch and reupload
Satellite collision: same as BYOP

**Comment by MS-githubaccnt** [comment]
I am working on this, could you assign it to me.

**Comment by yashrajbharti** [comment]
@MS-githubaccnt  BYOP still needs a fix, I want just the icon, no text , the way its in the screenshot
<img width="100" alt="Screenshot 2024-12-10 at 11 37 44 AM" src="https://github.com/user-attachments/assets/c7bba5b0-c039-4e62-828e-fc31d02d4725">
